// RestoOS API types — generated by hand to mirror the Go DTOs in
// internal/domain/*/{request,response}.go. Keep in sync with api-reference.md
// when the API contract changes.
//
// Conventions (see README.md for the full rationale):
//   - All money fields are integers in minor currency units (never floats).
//   - All timestamps are RFC 3339 strings in UTC.
//   - Tenant-scoped requests must carry an `X-Restaurant-ID` header.

// ---------------------------------------------------------------------------
// Shared envelopes
// ---------------------------------------------------------------------------

export interface PaginatedResult<T> {
  items: T[];
  page: number;
  pageSize: number;
  totalItems: number;
  totalPages: number;
}

export interface ApiError {
  error: string;
}

export interface PageQuery {
  page?: number;
  page_size?: number;
}

// ---------------------------------------------------------------------------
// Platform admin — Restaurant (platform-level, not tenant-scoped)
// ---------------------------------------------------------------------------

export type RestaurantStatus = "active" | "suspended";
export type RestaurantPlan = "standard" | "pro" | "enterprise" | string;

export interface Restaurant {
  id: string;
  name: string;
  slug: string;
  address: string;
  phone: string;
  status: RestaurantStatus;
  plan: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateRestaurantRequest {
  name: string;
  slug: string;
  address?: string;
  phone?: string;
  plan?: RestaurantPlan;
}

export type UpdateRestaurantRequest = CreateRestaurantRequest;

export interface SetRestaurantStatusRequest {
  status: RestaurantStatus;
}

// ---------------------------------------------------------------------------
// Category
// ---------------------------------------------------------------------------

export interface Category {
  id: string;
  name: string;
  emoji: string;
  color: string;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface CreateCategoryRequest {
  name: string;
  emoji?: string;
  color?: string;
  sortOrder?: number;
}

export type UpdateCategoryRequest = CreateCategoryRequest;

// ---------------------------------------------------------------------------
// Ingredient
// ---------------------------------------------------------------------------

export interface Ingredient {
  id: string;
  name: string;
  unit: string;
  onHandQty: number;
  parLevel: number;
  unitCost: number; // minor units, weighted-average — managed, not directly editable
  isLowStock: boolean; // derived: onHandQty < parLevel
  createdAt: string;
  updatedAt: string;
}

export interface CreateIngredientRequest {
  name: string;
  unit: string;
  onHandQty?: number;
  parLevel?: number;
  unitCost?: number;
}

export interface UpdateIngredientRequest {
  name: string;
  unit: string;
  parLevel: number;
  // onHandQty / unitCost intentionally absent — see AdjustStockRequest,
  // stock-ins, and factor settlement for how they change.
}

export interface AdjustStockRequest {
  delta: number; // signed correction applied to onHandQty
  reason?: string;
}

// ---------------------------------------------------------------------------
// Food + recipe
// ---------------------------------------------------------------------------

export interface Food {
  id: string;
  categoryId: string;
  name: string;
  price: number; // minor units
  description: string;
  photoUrl: string;
  isActive: boolean;
  showOnMenu: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CreateFoodRequest {
  categoryId: string;
  name: string;
  price: number;
  description?: string;
  photoUrl?: string;
  isActive?: boolean; // defaults to true server-side
  showOnMenu?: boolean; // defaults to true server-side
}

export interface UpdateFoodRequest {
  categoryId: string;
  name: string;
  price: number;
  description?: string;
  photoUrl?: string;
  isActive: boolean;
  showOnMenu: boolean;
}

export interface UpsertRecipeLineRequest {
  ingredientId: string;
  qtyPerPortion: number;
  unit: string;
}

export interface RecipeLine {
  ingredientId: string;
  ingredientName: string;
  qtyPerPortion: number;
  unit: string;
  unitCost: number; // ingredient's CURRENT weighted-average cost, minor units
  lineCost: number; // round(qtyPerPortion × unitCost)
}

/** Food enriched with its recipe and the live cost & margin summary. Always
 * recomputed from each ingredient's current cost — never cached. */
export interface FoodDetail extends Food {
  recipe: RecipeLine[];
  foodCost: number; // Σ lineCost
  margin: number; // 1 − foodCost / price, in [0,1]; 0 when price is 0
}

// ---------------------------------------------------------------------------
// Stock-in (receiving)
// ---------------------------------------------------------------------------

export interface StockInLine {
  ingredientId: string;
  qty: number;
  unit: string;
  unitCost: number;
  lineTotal: number; // round(unitCost × qty)
}

export interface StockIn {
  id: string;
  supplier: string;
  occurredOn: string; // date (RFC 3339)
  invoiceNo: string;
  grandTotal: number; // Σ lineTotal
  lines: StockInLine[];
  createdAt: string;
}

export interface CreateStockInLineRequest {
  ingredientId: string;
  qty: number;
  unit: string;
  unitCost: number;
}

export interface CreateStockInRequest {
  supplier: string;
  occurredOn: string;
  invoiceNo?: string;
  lines: CreateStockInLineRequest[]; // at least one
}

// ---------------------------------------------------------------------------
// Guest (loyalty CRM)
// ---------------------------------------------------------------------------

export type GuestTier = "member" | "silver" | "gold" | "platinum";

export interface Guest {
  id: string;
  name: string;
  phone: string;
  tier: GuestTier; // derived — auto-promotes on settlement by visit count
  visits: number; // managed — incremented on settlement
  lifetimeSpend: number; // managed — accrued on settlement, minor units
  lastSeenAt: string | null; // managed — set to settlement time
  createdAt: string;
  updatedAt: string;
}

export interface CreateGuestRequest {
  name: string;
  phone: string;
}

export type UpdateGuestRequest = CreateGuestRequest;

// ---------------------------------------------------------------------------
// Factor (order / invoice)
// ---------------------------------------------------------------------------

export type FactorStatus = "unpaid" | "paid";

export interface FactorLine {
  id: string;
  foodId: string;
  qty: number;
  unitPrice: number; // captured at order time — immune to later menu price changes
  lineTotal: number; // unitPrice × qty
}

export interface Factor {
  id: string;
  tableId: string;
  guestId: string | null;
  subtotal: number; // Σ lineTotal
  servicePct: number; // percentage value, e.g. 10 means 10%
  vatPct: number;
  total: number; // subtotal + subtotal×servicePct% + subtotal×vatPct%
  status: FactorStatus;
  printedAt: string | null;
  lines: FactorLine[];
  createdAt: string;
  updatedAt: string;
}

export interface FactorLineRequest {
  foodId: string;
  qty: number;
  // unitPrice is intentionally absent — the server resolves it from the
  // food's current price so clients can never spoof pricing.
}

export interface CreateFactorRequest {
  tableId: string;
  guestId?: string | null;
  servicePct: number;
  vatPct: number;
  lines: FactorLineRequest[]; // at least one
}

export type UpdateFactorRequest = CreateFactorRequest;
